server:
  port: 9100

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./h2/demodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql.init.mode: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update