CREATE TABLE IF NOT EXISTS account (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    email VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS message (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT NOT NULL,
    millis BIGINT NOT NULL,
    blabla VARCHAR(512) NOT NULL
);